name: .NET Build & Test

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: [ '8.0', '9.0', '10.0' ]

    env:
      DOTNET_VERSION: ${{ matrix.dotnet }}

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Setup .NET
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --framework=net"$DOTNET_VERSION" --no-restore
    - name: Test
      run: dotnet test --framework=net"$DOTNET_VERSION" --no-build --verbosity normal --collect:"XPlat Code Coverage"
    - name: Upload coverage reports to Codecov
      if: ${{ matrix.dotnet == '8.0' }}
      uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
